name: Java CI with Maven and pmd

on:
  push:
    tags:
      - rc-*.*

jobs:   
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Validate with Maven
      run: mvn validate
    - name: Compile with Maven
      run: mvn compile
    - name: Run PMD
      id: pmd
      uses: pmd/pmd-github-action@v1
      with:
          rulesets: 'rulesets.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: pmd-report.sarif
    - name: Test with Maven
      run: mvn test
    - name: Tag build
      run: |
          git config --global user.email "leonandrogurgel@gmail.com"
          git config --global user.name "Leonandro"
          git tag -a
